stages:
  - build
  - error

building-tez-service:
  stage: build
  tags:
    - dev36
  only:
    - dev
  script:
    - mvn clean package
    
error-test:
  stage: error
  only:
    - dev
  tags:
    - dev36
  script:
    - echo "error"
  when: on_failure
