stages:
  - build
  - error

building-tez-uaa:
  stage: build
  tags:
    - dev36
  only:
    - dev
  script:
    - mvn clean package
    - sudo /root/TezCustoms/scripts/deploy_uaa.sh

error-test:
  stage: error
  only:
    - dev
  tags:
    - dev36
  script:
    - echo "Error"
  when: on_failure
