stages:
  - build
  - error

building-tez-service:
  stage: build
  tags:
    - dev36
  only:
    - dev
  script:
    - mvn clean package
    - sudo /root/TezCustoms/scripts/deploy_service.sh
    - curl "https://api.telegram.org/bot5576851566:AAE3yAb0b7Rd5mGFw2_mIiZpGdAR4s-FShE/sendMessage?chat_id=-674806486&text=Service+build+is+successful+✅"
    
error-test:
  stage: error
  only:
    - dev
  tags:
    - dev36
  script:
    - curl "https://api.telegram.org/bot5576851566:AAE3yAb0b7Rd5mGFw2_mIiZpGdAR4s-FShE/sendMessage?chat_id=-674806486&text=Service+build+is+failed+🆘"
  when: on_failure
