package kz.ne.railways.tezcustoms.service.constants.errors;

public interface Errors {
    String UNSUPPORTED_MEDIA_TYPE = "FILE_NOT_SUPPORTED";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String INVOICE_EXISTS = "INVOICE_EXISTS";
    String INVALID_PARAMETERS = "INVALID_PARAMETERS_SUPPLIED";
    String STATION_NOT_FOUND = "STATION_NOT_FOUND";
    String COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND";
    String CUSTOM_ORGAN_NOT_FOUND = "CUSTOM_ORGAN_NOT_FOUND";
    String TRANSIT_CODE_NOT_FOUND = "TRANSIT_CODE_NOT_FOUND";
    String IIN_TAKEN = "IIN/BIN_ALREADY_TAKEN";
    String EMAIL_IN_USE = "EMAIL_ALREADY_IN_USE";
    String ROLE_CANNOT_BE_EMPTY = "ROLE_CANNOT_BE_EMPTY";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String INVALID_ROLE = "NOT_VALID_ROLE";
    String INVALID_USER = "NOT_VALID_USER";
    String IIN_NOT_MATCH = "IIN/BIN_NOT_MATCH";
    String MALFORMED_JSON_REQUEST = "MALFORMED_JSON_REQUEST";
    String EMAIL_IS_ACTIVATED = "INVALID_ACTIVATION_KEY";
    String EMAIL_NOT_ACTIVATED = "EMAIL_NOT_ACTIVATED";
    String ACTIVATION_CODE_IS_EXPIRED = "ACTIVATION_CODE_IS_EXPIRED";
    String SERVICE_IS_UNAVAILABLE = "SERVICE_IS_UNAVAILABLE";
    String COMPANY_NOT_FOUND_BY_BIN = "COMPANY_NOT_FOUND_BY_BIN";
    String TNVED_CODES_NOT_FOUND = "TNVED_CODES_NOT_FOUND";
}
